packages:
  - 'examples/*'
  - 'packages/*'
  - 'packages/livekit-rtc/npm/*'

catalog:
  "@bufbuild/protobuf": 1.10.1
  "@bufbuild/protoc-gen-es": 1.10.1
  "@livekit/mutex": ^1.0.0
  "@livekit/protocol": ^1.41.0
  "@livekit/typed-emitter": ^3.0.0
  "@types/node": ^22.13.10
  prettier: ^3.5.3
  tsup: ^8.3.5
  typedoc: ^0.28.0
  typescript: 5.8.2
  vite: ^7.1.3
  vitest: ^3.2.4
 


