packages:
  - 'examples/*'
  - 'packages/*'
  - 'packages/livekit-rtc/npm/*'

minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - '@livekit/*'
  # Renovate security update: vite@6.4.2
  - vite@6.4.2
