// Copyright 2023 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v2.2.0 with parameter "target=ts,import_extension=js"
// @generated from file participant.proto (package livekit.proto, syntax proto2)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { FfiOwnedHandle } from "./handle_pb.js";
import { file_handle } from "./handle_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file participant.proto.
 */
export const file_participant: GenFile = /*@__PURE__*/
  fileDesc("ChFwYXJ0aWNpcGFudC5wcm90bxINbGl2ZWtpdC5wcm90byL1AQoPUGFydGljaXBhbnRJbmZvEgsKA3NpZBgBIAIoCRIMCgRuYW1lGAIgAigJEhAKCGlkZW50aXR5GAMgAigJEhAKCG1ldGFkYXRhGAQgAigJEkIKCmF0dHJpYnV0ZXMYBSADKAsyLi5saXZla2l0LnByb3RvLlBhcnRpY2lwYW50SW5mby5BdHRyaWJ1dGVzRW50cnkSLAoEa2luZBgGIAIoDjIeLmxpdmVraXQucHJvdG8uUGFydGljaXBhbnRLaW5kGjEKD0F0dHJpYnV0ZXNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBIm8KEE93bmVkUGFydGljaXBhbnQSLQoGaGFuZGxlGAEgAigLMh0ubGl2ZWtpdC5wcm90by5GZmlPd25lZEhhbmRsZRIsCgRpbmZvGAIgAigLMh4ubGl2ZWtpdC5wcm90by5QYXJ0aWNpcGFudEluZm8qoQEKD1BhcnRpY2lwYW50S2luZBIdChlQQVJUSUNJUEFOVF9LSU5EX1NUQU5EQVJEEAASHAoYUEFSVElDSVBBTlRfS0lORF9JTkdSRVNTEAESGwoXUEFSVElDSVBBTlRfS0lORF9FR1JFU1MQAhIYChRQQVJUSUNJUEFOVF9LSU5EX1NJUBADEhoKFlBBUlRJQ0lQQU5UX0tJTkRfQUdFTlQQBEIQqgINTGl2ZUtpdC5Qcm90bw", [file_handle]);

/**
 * @generated from message livekit.proto.ParticipantInfo
 */
export type ParticipantInfo = Message<"livekit.proto.ParticipantInfo"> & {
  /**
   * @generated from field: required string sid = 1;
   */
  sid: string;

  /**
   * @generated from field: required string name = 2;
   */
  name: string;

  /**
   * @generated from field: required string identity = 3;
   */
  identity: string;

  /**
   * @generated from field: required string metadata = 4;
   */
  metadata: string;

  /**
   * @generated from field: map<string, string> attributes = 5;
   */
  attributes: { [key: string]: string };

  /**
   * @generated from field: required livekit.proto.ParticipantKind kind = 6;
   */
  kind: ParticipantKind;
};

/**
 * Describes the message livekit.proto.ParticipantInfo.
 * Use `create(ParticipantInfoSchema)` to create a new message.
 */
export const ParticipantInfoSchema: GenMessage<ParticipantInfo> = /*@__PURE__*/
  messageDesc(file_participant, 0);

/**
 * @generated from message livekit.proto.OwnedParticipant
 */
export type OwnedParticipant = Message<"livekit.proto.OwnedParticipant"> & {
  /**
   * @generated from field: required livekit.proto.FfiOwnedHandle handle = 1;
   */
  handle?: FfiOwnedHandle;

  /**
   * @generated from field: required livekit.proto.ParticipantInfo info = 2;
   */
  info?: ParticipantInfo;
};

/**
 * Describes the message livekit.proto.OwnedParticipant.
 * Use `create(OwnedParticipantSchema)` to create a new message.
 */
export const OwnedParticipantSchema: GenMessage<OwnedParticipant> = /*@__PURE__*/
  messageDesc(file_participant, 1);

/**
 * @generated from enum livekit.proto.ParticipantKind
 */
export enum ParticipantKind {
  /**
   * @generated from enum value: PARTICIPANT_KIND_STANDARD = 0;
   */
  STANDARD = 0,

  /**
   * @generated from enum value: PARTICIPANT_KIND_INGRESS = 1;
   */
  INGRESS = 1,

  /**
   * @generated from enum value: PARTICIPANT_KIND_EGRESS = 2;
   */
  EGRESS = 2,

  /**
   * @generated from enum value: PARTICIPANT_KIND_SIP = 3;
   */
  SIP = 3,

  /**
   * @generated from enum value: PARTICIPANT_KIND_AGENT = 4;
   */
  AGENT = 4,
}

/**
 * Describes the enum livekit.proto.ParticipantKind.
 */
export const ParticipantKindSchema: GenEnum<ParticipantKind> = /*@__PURE__*/
  enumDesc(file_participant, 0);

