// Copyright 2023 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file rpc.proto (package livekit.proto, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message livekit.proto.RpcError
 */
export class RpcError extends Message<RpcError> {
  /**
   * @generated from field: uint32 code = 1;
   */
  code = 0;

  /**
   * @generated from field: string message = 2;
   */
  message = "";

  /**
   * @generated from field: string data = 3;
   */
  data = "";

  constructor(data?: PartialMessage<RpcError>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "livekit.proto.RpcError";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "code", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "data", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RpcError {
    return new RpcError().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RpcError {
    return new RpcError().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RpcError {
    return new RpcError().fromJsonString(jsonString, options);
  }

  static equals(a: RpcError | PlainMessage<RpcError> | undefined, b: RpcError | PlainMessage<RpcError> | undefined): boolean {
    return proto3.util.equals(RpcError, a, b);
  }
}

/**
 * FFI Requests
 *
 * @generated from message livekit.proto.PerformRpcRequestRequest
 */
export class PerformRpcRequestRequest extends Message<PerformRpcRequestRequest> {
  /**
   * @generated from field: uint64 local_participant_handle = 1;
   */
  localParticipantHandle = protoInt64.zero;

  /**
   * @generated from field: string destination_identity = 2;
   */
  destinationIdentity = "";

  /**
   * @generated from field: string method = 3;
   */
  method = "";

  /**
   * @generated from field: string payload = 4;
   */
  payload = "";

  /**
   * @generated from field: optional uint32 response_timeout_ms = 5;
   */
  responseTimeoutMs?: number;

  constructor(data?: PartialMessage<PerformRpcRequestRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "livekit.proto.PerformRpcRequestRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "local_participant_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "destination_identity", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "method", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "payload", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "response_timeout_ms", kind: "scalar", T: 13 /* ScalarType.UINT32 */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PerformRpcRequestRequest {
    return new PerformRpcRequestRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PerformRpcRequestRequest {
    return new PerformRpcRequestRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PerformRpcRequestRequest {
    return new PerformRpcRequestRequest().fromJsonString(jsonString, options);
  }

  static equals(a: PerformRpcRequestRequest | PlainMessage<PerformRpcRequestRequest> | undefined, b: PerformRpcRequestRequest | PlainMessage<PerformRpcRequestRequest> | undefined): boolean {
    return proto3.util.equals(PerformRpcRequestRequest, a, b);
  }
}

/**
 * @generated from message livekit.proto.RegisterRpcMethodRequest
 */
export class RegisterRpcMethodRequest extends Message<RegisterRpcMethodRequest> {
  /**
   * @generated from field: uint64 local_participant_handle = 1;
   */
  localParticipantHandle = protoInt64.zero;

  /**
   * @generated from field: string method = 2;
   */
  method = "";

  constructor(data?: PartialMessage<RegisterRpcMethodRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "livekit.proto.RegisterRpcMethodRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "local_participant_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "method", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RegisterRpcMethodRequest {
    return new RegisterRpcMethodRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RegisterRpcMethodRequest {
    return new RegisterRpcMethodRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RegisterRpcMethodRequest {
    return new RegisterRpcMethodRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RegisterRpcMethodRequest | PlainMessage<RegisterRpcMethodRequest> | undefined, b: RegisterRpcMethodRequest | PlainMessage<RegisterRpcMethodRequest> | undefined): boolean {
    return proto3.util.equals(RegisterRpcMethodRequest, a, b);
  }
}

/**
 * @generated from message livekit.proto.UnregisterRpcMethodRequest
 */
export class UnregisterRpcMethodRequest extends Message<UnregisterRpcMethodRequest> {
  /**
   * @generated from field: uint64 local_participant_handle = 1;
   */
  localParticipantHandle = protoInt64.zero;

  /**
   * @generated from field: string method = 2;
   */
  method = "";

  constructor(data?: PartialMessage<UnregisterRpcMethodRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "livekit.proto.UnregisterRpcMethodRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "local_participant_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "method", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UnregisterRpcMethodRequest {
    return new UnregisterRpcMethodRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UnregisterRpcMethodRequest {
    return new UnregisterRpcMethodRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UnregisterRpcMethodRequest {
    return new UnregisterRpcMethodRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UnregisterRpcMethodRequest | PlainMessage<UnregisterRpcMethodRequest> | undefined, b: UnregisterRpcMethodRequest | PlainMessage<UnregisterRpcMethodRequest> | undefined): boolean {
    return proto3.util.equals(UnregisterRpcMethodRequest, a, b);
  }
}

/**
 * @generated from message livekit.proto.RpcMethodInvocationResponseRequest
 */
export class RpcMethodInvocationResponseRequest extends Message<RpcMethodInvocationResponseRequest> {
  /**
   * @generated from field: uint64 local_participant_handle = 1;
   */
  localParticipantHandle = protoInt64.zero;

  /**
   * @generated from field: uint64 invocation_id = 2;
   */
  invocationId = protoInt64.zero;

  /**
   * @generated from field: optional string payload = 3;
   */
  payload?: string;

  /**
   * @generated from field: optional livekit.proto.RpcError error = 4;
   */
  error?: RpcError;

  constructor(data?: PartialMessage<RpcMethodInvocationResponseRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "livekit.proto.RpcMethodInvocationResponseRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "local_participant_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "invocation_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "payload", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "error", kind: "message", T: RpcError, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RpcMethodInvocationResponseRequest {
    return new RpcMethodInvocationResponseRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RpcMethodInvocationResponseRequest {
    return new RpcMethodInvocationResponseRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RpcMethodInvocationResponseRequest {
    return new RpcMethodInvocationResponseRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RpcMethodInvocationResponseRequest | PlainMessage<RpcMethodInvocationResponseRequest> | undefined, b: RpcMethodInvocationResponseRequest | PlainMessage<RpcMethodInvocationResponseRequest> | undefined): boolean {
    return proto3.util.equals(RpcMethodInvocationResponseRequest, a, b);
  }
}

/**
 * FFI Responses
 *
 * @generated from message livekit.proto.PerformRpcRequestResponse
 */
export class PerformRpcRequestResponse extends Message<PerformRpcRequestResponse> {
  /**
   * @generated from field: uint64 async_id = 1;
   */
  asyncId = protoInt64.zero;

  constructor(data?: PartialMessage<PerformRpcRequestResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "livekit.proto.PerformRpcRequestResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PerformRpcRequestResponse {
    return new PerformRpcRequestResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PerformRpcRequestResponse {
    return new PerformRpcRequestResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PerformRpcRequestResponse {
    return new PerformRpcRequestResponse().fromJsonString(jsonString, options);
  }

  static equals(a: PerformRpcRequestResponse | PlainMessage<PerformRpcRequestResponse> | undefined, b: PerformRpcRequestResponse | PlainMessage<PerformRpcRequestResponse> | undefined): boolean {
    return proto3.util.equals(PerformRpcRequestResponse, a, b);
  }
}

/**
 * @generated from message livekit.proto.RegisterRpcMethodResponse
 */
export class RegisterRpcMethodResponse extends Message<RegisterRpcMethodResponse> {
  /**
   * @generated from field: uint64 async_id = 1;
   */
  asyncId = protoInt64.zero;

  constructor(data?: PartialMessage<RegisterRpcMethodResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "livekit.proto.RegisterRpcMethodResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RegisterRpcMethodResponse {
    return new RegisterRpcMethodResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RegisterRpcMethodResponse {
    return new RegisterRpcMethodResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RegisterRpcMethodResponse {
    return new RegisterRpcMethodResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RegisterRpcMethodResponse | PlainMessage<RegisterRpcMethodResponse> | undefined, b: RegisterRpcMethodResponse | PlainMessage<RegisterRpcMethodResponse> | undefined): boolean {
    return proto3.util.equals(RegisterRpcMethodResponse, a, b);
  }
}

/**
 * @generated from message livekit.proto.UnregisterRpcMethodResponse
 */
export class UnregisterRpcMethodResponse extends Message<UnregisterRpcMethodResponse> {
  /**
   * @generated from field: uint64 async_id = 1;
   */
  asyncId = protoInt64.zero;

  constructor(data?: PartialMessage<UnregisterRpcMethodResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "livekit.proto.UnregisterRpcMethodResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UnregisterRpcMethodResponse {
    return new UnregisterRpcMethodResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UnregisterRpcMethodResponse {
    return new UnregisterRpcMethodResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UnregisterRpcMethodResponse {
    return new UnregisterRpcMethodResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UnregisterRpcMethodResponse | PlainMessage<UnregisterRpcMethodResponse> | undefined, b: UnregisterRpcMethodResponse | PlainMessage<UnregisterRpcMethodResponse> | undefined): boolean {
    return proto3.util.equals(UnregisterRpcMethodResponse, a, b);
  }
}

/**
 * @generated from message livekit.proto.RpcMethodInvocationResponseResponse
 */
export class RpcMethodInvocationResponseResponse extends Message<RpcMethodInvocationResponseResponse> {
  /**
   * @generated from field: uint64 async_id = 1;
   */
  asyncId = protoInt64.zero;

  constructor(data?: PartialMessage<RpcMethodInvocationResponseResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "livekit.proto.RpcMethodInvocationResponseResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RpcMethodInvocationResponseResponse {
    return new RpcMethodInvocationResponseResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RpcMethodInvocationResponseResponse {
    return new RpcMethodInvocationResponseResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RpcMethodInvocationResponseResponse {
    return new RpcMethodInvocationResponseResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RpcMethodInvocationResponseResponse | PlainMessage<RpcMethodInvocationResponseResponse> | undefined, b: RpcMethodInvocationResponseResponse | PlainMessage<RpcMethodInvocationResponseResponse> | undefined): boolean {
    return proto3.util.equals(RpcMethodInvocationResponseResponse, a, b);
  }
}

/**
 * FFI Callbacks
 *
 * @generated from message livekit.proto.PerformRpcRequestCallback
 */
export class PerformRpcRequestCallback extends Message<PerformRpcRequestCallback> {
  /**
   * @generated from field: uint64 async_id = 1;
   */
  asyncId = protoInt64.zero;

  /**
   * @generated from field: optional string payload = 2;
   */
  payload?: string;

  /**
   * @generated from field: optional livekit.proto.RpcError error = 3;
   */
  error?: RpcError;

  constructor(data?: PartialMessage<PerformRpcRequestCallback>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "livekit.proto.PerformRpcRequestCallback";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "payload", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "error", kind: "message", T: RpcError, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PerformRpcRequestCallback {
    return new PerformRpcRequestCallback().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PerformRpcRequestCallback {
    return new PerformRpcRequestCallback().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PerformRpcRequestCallback {
    return new PerformRpcRequestCallback().fromJsonString(jsonString, options);
  }

  static equals(a: PerformRpcRequestCallback | PlainMessage<PerformRpcRequestCallback> | undefined, b: PerformRpcRequestCallback | PlainMessage<PerformRpcRequestCallback> | undefined): boolean {
    return proto3.util.equals(PerformRpcRequestCallback, a, b);
  }
}

/**
 * @generated from message livekit.proto.RegisterRpcMethodCallback
 */
export class RegisterRpcMethodCallback extends Message<RegisterRpcMethodCallback> {
  /**
   * @generated from field: uint64 async_id = 1;
   */
  asyncId = protoInt64.zero;

  constructor(data?: PartialMessage<RegisterRpcMethodCallback>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "livekit.proto.RegisterRpcMethodCallback";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RegisterRpcMethodCallback {
    return new RegisterRpcMethodCallback().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RegisterRpcMethodCallback {
    return new RegisterRpcMethodCallback().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RegisterRpcMethodCallback {
    return new RegisterRpcMethodCallback().fromJsonString(jsonString, options);
  }

  static equals(a: RegisterRpcMethodCallback | PlainMessage<RegisterRpcMethodCallback> | undefined, b: RegisterRpcMethodCallback | PlainMessage<RegisterRpcMethodCallback> | undefined): boolean {
    return proto3.util.equals(RegisterRpcMethodCallback, a, b);
  }
}

/**
 * @generated from message livekit.proto.UnregisterRpcMethodCallback
 */
export class UnregisterRpcMethodCallback extends Message<UnregisterRpcMethodCallback> {
  /**
   * @generated from field: uint64 async_id = 1;
   */
  asyncId = protoInt64.zero;

  constructor(data?: PartialMessage<UnregisterRpcMethodCallback>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "livekit.proto.UnregisterRpcMethodCallback";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UnregisterRpcMethodCallback {
    return new UnregisterRpcMethodCallback().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UnregisterRpcMethodCallback {
    return new UnregisterRpcMethodCallback().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UnregisterRpcMethodCallback {
    return new UnregisterRpcMethodCallback().fromJsonString(jsonString, options);
  }

  static equals(a: UnregisterRpcMethodCallback | PlainMessage<UnregisterRpcMethodCallback> | undefined, b: UnregisterRpcMethodCallback | PlainMessage<UnregisterRpcMethodCallback> | undefined): boolean {
    return proto3.util.equals(UnregisterRpcMethodCallback, a, b);
  }
}

/**
 * @generated from message livekit.proto.RpcMethodInvocationResponseCallback
 */
export class RpcMethodInvocationResponseCallback extends Message<RpcMethodInvocationResponseCallback> {
  /**
   * @generated from field: uint64 async_id = 1;
   */
  asyncId = protoInt64.zero;

  constructor(data?: PartialMessage<RpcMethodInvocationResponseCallback>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "livekit.proto.RpcMethodInvocationResponseCallback";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RpcMethodInvocationResponseCallback {
    return new RpcMethodInvocationResponseCallback().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RpcMethodInvocationResponseCallback {
    return new RpcMethodInvocationResponseCallback().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RpcMethodInvocationResponseCallback {
    return new RpcMethodInvocationResponseCallback().fromJsonString(jsonString, options);
  }

  static equals(a: RpcMethodInvocationResponseCallback | PlainMessage<RpcMethodInvocationResponseCallback> | undefined, b: RpcMethodInvocationResponseCallback | PlainMessage<RpcMethodInvocationResponseCallback> | undefined): boolean {
    return proto3.util.equals(RpcMethodInvocationResponseCallback, a, b);
  }
}

/**
 * FFI Events
 *
 * @generated from message livekit.proto.RpcMethodInvocationEvent
 */
export class RpcMethodInvocationEvent extends Message<RpcMethodInvocationEvent> {
  /**
   * @generated from field: uint64 local_participant_handle = 1;
   */
  localParticipantHandle = protoInt64.zero;

  /**
   * @generated from field: uint64 invocation_id = 2;
   */
  invocationId = protoInt64.zero;

  /**
   * @generated from field: string method = 3;
   */
  method = "";

  /**
   * @generated from field: string request_id = 4;
   */
  requestId = "";

  /**
   * @generated from field: string participant_identity = 5;
   */
  participantIdentity = "";

  /**
   * @generated from field: string payload = 6;
   */
  payload = "";

  /**
   * @generated from field: uint32 timeout_ms = 7;
   */
  timeoutMs = 0;

  constructor(data?: PartialMessage<RpcMethodInvocationEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "livekit.proto.RpcMethodInvocationEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "local_participant_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "invocation_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "method", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "request_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "payload", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "timeout_ms", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RpcMethodInvocationEvent {
    return new RpcMethodInvocationEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RpcMethodInvocationEvent {
    return new RpcMethodInvocationEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RpcMethodInvocationEvent {
    return new RpcMethodInvocationEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RpcMethodInvocationEvent | PlainMessage<RpcMethodInvocationEvent> | undefined, b: RpcMethodInvocationEvent | PlainMessage<RpcMethodInvocationEvent> | undefined): boolean {
    return proto3.util.equals(RpcMethodInvocationEvent, a, b);
  }
}

