[project]
name = "python-inbound-sip"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.8.0",
    "livekit>=1.0.7",
    "livekit-api>=1.0.3",
]
